# Site settings
title: Sascha's Blog
email: mundstein@post.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  I am blogging sporadically here about what I find intersting, mainly 
  concerning iOS and Swift.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social sharing links for footer
twitter_username: mundstein
github_username:  # mundipf
stackoverflow_username: mundi
stackoverflow_userid: 427083

# Include directory
include: ['_pages']

# Build settings
markdown: kramdown
